### ISSUE TITLE
Make the Minimum-error thresholding work with floats?

### ISSUE THREAD

**Issue by h4k1m0u** [fiji/Auto_Threshold#7]
Hi,

Thanks for publishing these thresholding algorithms open-source.
I translated the Minimum-error thresholding (Kittler and Illingworth 1986) to python, but it's not possible to perform the thresholding on float images.

Is it possible to modify it a bit to adapt it to float images?

Thanks.

Hakim.

**Comment by landinig** [comment]
Not really.  You can only apply these methods to *histograms* of images, so any float image needs to be 'binned' into a discrete histogram..
You can, however, convert your floating point image to integer (8 or 16 bit images) and then threshold that.

**Comment by h4k1m0u** [comment]
Actually, I can convert my float image to `dB` (and then to int) but I will get negative values on the log image. Maybe if I shift the log image towards positive values, it might work.
Thanks.

**Comment by landinig** [comment]
Have a look In ImageJ, you can convert directly from 32bit to 8 or 16 bit and that will take care of the offset.
